# Generated by Django 5.2.5 on 2025-09-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_usuario',
            field=models.CharField(choices=[('MONITOR', 'Monitor'), ('DIRECTIVO', 'Directivo')], default='MONITOR', max_length=10),
        ),
    ]
