# Generated by Django 5.2.5 on 2025-09-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_usuariopersonalizado_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado_autorizacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
