# Generated by Django 5.2.5 on 2025-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_asistencia_estado_autorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Horas trabajadas en esta jornada', max_digits=4),
        ),
    ]
