# Generated by Django 5.2.5 on 2025-09-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_asistencia_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del ajuste de horas')),
                ('cantidad_horas', models.DecimalField(decimal_places=2, help_text='Cantidad de horas a ajustar (positivo para agregar, negativo para restar)', max_digits=5)),
                ('motivo', models.TextField(help_text='Razón del ajuste de horas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del ajuste')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('asistencia', models.ForeignKey(blank=True, help_text='Asistencia relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_horas', to='example.asistencia')),
                ('creado_por', models.ForeignKey(help_text='Directivo que realizó el ajuste', limit_choices_to={'tipo_usuario': 'DIRECTIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_creados', to='example.usuariopersonalizado')),
                ('usuario', models.ForeignKey(help_text='Monitor al que se le ajustan las horas', limit_choices_to={'tipo_usuario': 'MONITOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_horas', to='example.usuariopersonalizado')),
            ],
            options={
                'verbose_name': 'Ajuste de Horas',
                'verbose_name_plural': 'Ajustes de Horas',
                'ordering': ['-created_at'],
            },
        ),
    ]
