# Generated by Django 4.1.3 on 2025-09-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_ajustehoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave única para identificar la configuración', max_length=50, unique=True)),
                ('valor', models.CharField(help_text='Valor de la configuración', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción de qué representa esta configuración')),
                ('tipo_dato', models.CharField(choices=[('decimal', 'Decimal'), ('entero', 'Entero'), ('texto', 'Texto'), ('booleano', 'Booleano')], default='texto', help_text='Tipo de dato de la configuración', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Directivo que creó esta configuración', limit_choices_to={'tipo_usuario': 'DIRECTIVO'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_creadas', to='example.usuariopersonalizado')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['clave'],
            },
        ),
    ]
