# Generated by Django 4.1.3 on 2025-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_configuracionsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado_autorizacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('recuperado', 'Recuperado')], default='pendiente', max_length=10),
        ),
    ]
